### ISSUE TITLE
Need to create a context ranker using TF-IDF

### ISSUE THREAD

**Issue by sriyavasudevan** [sriyavasudevan/Question-Answering-System#1]
Pending task

**Comment by Eva23M** [comment]
c11f278ca5a17e26d98531ea7c11762b503352cc had uploaded the first version of tf-idf method, could run to search the top 2 documents for a specific question but failed to find the true document we need. Still need to find improve this method in order to find the right document we want.

**Comment by sriyavasudevan** [comment]
Try feeding in the top 2 ranks into bert model directly to see if it improves answer @xuechunf

**Comment by Eva23M** [comment]
3d56d03eb01f8a201b526a2891741e93a2243083 added some comment lines for content ranker

**Comment by sriyavasudevan** [comment]
compeleted
