### ISSUE TITLE
Replace hyperlinks with "link#" to be able to print out that link in the output

### ISSUE THREAD

**Issue by sriyavasudevan** [sriyavasudevan/Question-Answering-System#11]
context: Bunny Rabbit link2 is here

dictionary
link2 --> "rabbit.com"

predicted answer - Bunny Rabbit link2 is here

if "link" in answer:
    hyperlink = dict['link2']

new_answer = Bunny Rabbit rabbit.com

**Comment by matthewspeciale** [comment]
Done. @sriyavasudevan please check a few examples to see if it's done the way it's supposed to

**Comment by sriyavasudevan** [comment]
@MattSpeciale737 sorry, have you pushed the changes?

**Comment by matthewspeciale** [comment]
Function added in the following commit caf53433c555c33fbcebab36e7ed0a24b22f768f. Needs further testing on actual answers.

**Comment by sriyavasudevan** [comment]
@sriyavasudevan  follow up with @matthewspeciale
