### ISSUE TITLE
Give slide number in the predicted answer

### ISSUE THREAD

**Issue by sriyavasudevan** [sriyavasudevan/Question-Answering-System#12]
Concatenate the slide # onto the predicted answer when displaying

retrieve first 4 words, if 3 and 4 are also numbers, give everything else, just the first 2

**Comment by Eva23M** [comment]
added the get slide number method d79963eb03d64c65859c1cf2e6cdc988fa5bcd29

**Comment by Eva23M** [comment]
Tested for slide number method and worked 82a6c0b01210e670bd733807b74f5eb03c3def4c

**Comment by sriyavasudevan** [comment]
@sriyavasudevan needs to fix the one very long context, test and close

**Comment by Eva23M** [comment]
fix the method 985d049644b09f089bd3f7baaec9787e0f5b81ad
