### ISSUE TITLE
Error for tokens over limit

### ISSUE THREAD

**Issue by Eva23M** [sriyavasudevan/Question-Answering-System#19]
When the answer that bert model returned is too long and the slide itself is quite long, the system will prompt an error for tokens over limit and not keep answering the following questions.

The error will be like this:
Token indices sequence length is longer than the specified maximum sequence length for this model (5** > 512). Running this sequence through the model will result in indexing errors
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

**Comment by sriyavasudevan** [comment]
Removed adding answer to history component since it takes up too much token space and does not improve model all that significantly with remembering history 54cf9661baf651760f25ab8c016975c677ce2d18 

@Eva23M please pull latest and test from your end as well.

**Comment by Eva23M** [comment]
tested and worked
