### ISSUE TITLE
Need to cut off history at 512 characters

### ISSUE THREAD

**Issue by sriyavasudevan** [sriyavasudevan/Question-Answering-System#3]

**Comment by sriyavasudevan** [comment]
Need to also test the response of bert when context is greater than 512 characters

**Comment by sriyavasudevan** [comment]
@MattSpeciale737 made a commit with these changes. Will need to be tested by others

**Comment by matthewspeciale** [comment]
> 

![image](https://user-images.githubusercontent.com/54867576/165805442-1888fc26-df96-4ba6-b88a-b2f01ff95cee.png)
This is the error message when the context is greater than 512 tokens.

**Comment by sriyavasudevan** [comment]
Added changes where entire questions from history get removed if total context is over 512 tokens. It removes oldest questions first. Commit - 8c74f1342117d79a946ef4d5e5bcf72a6caba283 

@MattSpeciale737 please test changes from your end

**Comment by sriyavasudevan** [comment]
Added changes where entire questions from history get removed if total context is over 512 tokens. It removes oldest questions first. Commit - 8c74f1342117d79a946ef4d5e5bcf72a6caba283

**Comment by sriyavasudevan** [comment]
Tested and completed
